###
GET http://47.106.158.254/admin/users?page=2&size=5  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc19hZG1pbiI6dHJ1ZSwic3ViIjoiMSIsInVzZXJfaWQiOjEsIm5pY2tuYW1lIjoi5bCP5ZWKIiwiYXZhdGFyIjpudWxsLCJleHAiOjE1Mzc0MDU0MjksImlhdCI6MTUzNjgwMDYyOSwianRpIjoiNzViNjJiMjctNDQ5YS00N2Q1LWFhZjUtOGI1ZmJiZGM5MTFhIiwidXNlcm5hbWUiOiJhMTIzNDU2In0.ckkGVGaevr4lAnThu1n4hWvRgvYESu2mQNXJ9XvwgJw

###
POST http://47.106.158.254/admin/forbiddens HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc19hZG1pbiI6dHJ1ZSwic3ViIjoiMSIsInVzZXJfaWQiOjEsIm5pY2tuYW1lIjoi5bCP5ZWKIiwiYXZhdGFyIjpudWxsLCJleHAiOjE1Mzc0MDQ1NDYsImlhdCI6MTUzNjc5OTc0NiwianRpIjoiMjRmNGM3ZTctMTZlMS00ZjAyLWEyZTktYThhZjhkMjk3NjFiIiwidXNlcm5hbWUiOiJhMTIzNDU2In0.bPs9nQJMIY5eZTUYdEuBfLa1rpllRIwCfuhy8rlJi8E
content-type: application/json

{
    "user_id": 1,
    "authority_id": 1
}

###
GET http://47.106.158.254/users/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc19hZG1pbiI6dHJ1ZSwic3ViIjoiMSIsInVzZXJfaWQiOjEsIm5pY2tuYW1lIjoi5bCP5ZWKIiwiYXZhdGFyIjpudWxsLCJleHAiOjE1Mzc0MDQ1NDYsImlhdCI6MTUzNjc5OTc0NiwianRpIjoiMjRmNGM3ZTctMTZlMS00ZjAyLWEyZTktYThhZjhkMjk3NjFiIiwidXNlcm5hbWUiOiJhMTIzNDU2In0.bPs9nQJMIY5eZTUYdEuBfLa1rpllRIwCfuhy8rlJi8E

###
GET http://47.106.158.254/admin/articles?category_id=1&page=1&size=30
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc19hZG1pbiI6dHJ1ZSwic3ViIjoiMSIsInVzZXJfaWQiOjEsIm5pY2tuYW1lIjoi5bCP5ZWKIiwiYXZhdGFyIjpudWxsLCJleHAiOjE1Mzc0MDQ1NDYsImlhdCI6MTUzNjc5OTc0NiwianRpIjoiMjRmNGM3ZTctMTZlMS00ZjAyLWEyZTktYThhZjhkMjk3NjFiIiwidXNlcm5hbWUiOiJhMTIzNDU2In0.bPs9nQJMIY5eZTUYdEuBfLa1rpllRIwCfuhy8rlJi8E
entities

